### ISSUE TITLE
Links on introduction page don't work on website

### ISSUE THREAD

**Issue by BigRoy** [LucaScheller/VFX-UsdSurvivalGuide#1]
On [this website](https://lucascheller.github.io/VFX-UsdSurvivalGuide/) the links that link locally within the site don't work - unless you browse to the site using [this url](https://lucascheller.github.io/VFX-UsdSurvivalGuide/introduction/overview.html).

```
Fails: https://lucascheller.github.io/VFX-UsdSurvivalGuide/
Works: https://lucascheller.github.io/VFX-UsdSurvivalGuide/introduction/overview.html
```

They seem to to link to for example: `../introduction/motivation.md` which takes the site from:
```https://lucascheller.github.io/VFX-UsdSurvivalGuide/```
to:
```https://lucascheller.github.io/introduction/motivation.md```

As such I assume the link has to be changed to `introduction/motivation.md` or alike. I wanted to create a PR for that. However, the current link **does** work in the previews on Github and will likely break the other URL that does work currently. As such I wasn't sure what the preferred way of fixing it was and instead opened this issue. :)

**Comment by LucaScheller** [comment]
Hey, thanks for flagging it. I don't have time to look into it in the next two weeks as I'm taking a small break after Siggraph. I'll look into it after, should hopefully be an easy fix.

**Comment by LucaScheller** [comment]
Should be fixed now, the links broke because the page was used as the index.html and introduction/overview.html at the same time. I moved the introduction/overview to be the index.html and re-directed the old page to index.html, that should hopefully do the trick :)
