### ISSUE TITLE
Vertical dynamic navigation bars makes copying code examples difficult

### ISSUE THREAD

**Issue by fxnut** [LucaScheller/VFX-UsdSurvivalGuide#3]
Hi Luca,
Great book! Thank you for writing this. I just wanted to report a UI issue that's getting in the way of using the code examples.

When trying to copy the code examples manually by dragging the mouse over the code, the left navigation bar appears when moving to the beginning of the line, meaning that you can't start the drag operation to highlight the code.

When trying to press the "copy code" button instead in the top-right corner, the right navigation bar appears, preventing you from clicking it.

I don't know how much control you have over the theme to be able to tweak that, but maybe the code example boxes can have their outer margins brought in a bit to avoid the issue.

This is on Mac OS Ventura (13.0.1) with Chrome (116.0.5845.110)

Many thanks,
Andy

**Comment by LucaScheller** [comment]
Hey, thanks for checking out the guide!

I did adjust the max content width here: https://github.com/LucaScheller/VFX-UsdSurvivalGuide/blob/main/docs/theme/ext/css/custom.css 

That's probably messing up the mouse over margins. On a 2k monitor (+ full screen window), it seems to work fine though.

I'll look into adjusting the stylessheet this upcoming week to work better with smaller windows/resolutions. (Either hide the navigation bars at small resolutions or adjust their width)

Cheers,
Luca

**Comment by fxnut** [comment]
Thanks Luca. I can't believe I didn't just try to make the window larger! Yes, that's a good workaround for now. I can confirm that it's only problematic when the window's smaller.

A

**Comment by LucaScheller** [comment]
I made them a bit slimmer now, let me know how that works for you! (You might have to ctrl+shift+r your page to reload the stylesheet cache).

**Comment by fxnut** [comment]
Yep, that's working nicely. Thanks Luca!
