### ISSUE TITLE
Issue in code provided in Guide Structure

### ISSUE THREAD

**Issue by DStarRaj** [LucaScheller/VFX-UsdSurvivalGuide#4]
Following the code given here
https://github.com/LucaScheller/VFX-UsdSurvivalGuide/blob/main/docs/src/introduction/structure.md?plain=1#L77

I faced the issue:
`AttributeError: type object 'Stage' has no attribute 'CreateAnonymous'`

I think the correct code would be:
`layer = Sdf.Layer.CreateAnonymous()`

**Comment by LucaScheller** [comment]
Thanks for catching the mistake, should be fixed now :)

**Comment by DStarRaj** [comment]
Thanks for the update, closing this issue.
