### ISSUE TITLE
Issue in code provided in 2.2.1 Paths

### ISSUE THREAD

**Issue by DStarRaj** [LucaScheller/VFX-UsdSurvivalGuide#5]
Following the code given here
https://github.com/LucaScheller/VFX-UsdSurvivalGuide/blob/main/code/core/elements.py#L59

I faced the issue:
`AttributeError: 'module' object has no attribute 'childDelimiter'`

I think the correct code would be:
`path = Sdf.Path(Sdf.Path.childDelimiter.join(["set", "bicycle"]))`

**Note:** If you want I can too raise a PR.

**Comment by LucaScheller** [comment]
Fixed, thanks for finding the error!
