### ISSUE TITLE
Issue in code provided in 2.2.1 Paths (2)

### ISSUE THREAD

**Issue by DStarRaj** [LucaScheller/VFX-UsdSurvivalGuide#6]
Following the code given here
https://github.com/LucaScheller/VFX-UsdSurvivalGuide/blob/main/code/core/elements.py#L153

I faced the issue:
`AttributeError: 'Path' object has no attribute 'GetAncestorRange'`

I think the correct code would be:
`    for parent_path in variant_path.GetAncestorsRange():`

Note: If you want I can too raise a PR.

**Comment by LucaScheller** [comment]
Fixed :), thanks!
