### ISSUE TITLE
Issue in code provided in 2.2.1 Paths (3)

### ISSUE THREAD

**Issue by DStarRaj** [LucaScheller/VFX-UsdSurvivalGuide#7]
There are few issues in the [Properties](https://lucascheller.github.io/VFX-UsdSurvivalGuide/core/elements/path.html#properties) code:

---
* https://github.com/LucaScheller/VFX-UsdSurvivalGuide/blob/main/code/core/elements.py#L108-L109

Issue:
`AttributeError: 'str' object has no attribute 'name'`
Possible Fixes:
```
path = Sdf.Path("/set/bicycle.tire:size")
property_name = path.name                 # Returns: 'tire:size'
```
---
* https://github.com/LucaScheller/VFX-UsdSurvivalGuide/blob/main/code/core/elements.py#L119

Issue:
`AttributeError: 'module' object has no attribute 'path'`
Possible Fixes:
```
last_element = Sdf.Path.StripNamespace("/set/bicycle.tire:size") # Returns: 'size'
```
---
* https://github.com/LucaScheller/VFX-UsdSurvivalGuide/blob/main/code/core/elements.py#L122

Issue:
<code>ArgumentError: Python argument types in
Path.GetPrimPath(Path, Path)
did not match C++ signature:
GetPrimPath(pxrInternal_v0_21__pxrReserved__::SdfPath {lvalue})</code>
Possible Fixes:
```
prim_path = path.GetPrimPath() # Returns: Sdf.Path('/set/bicycle')
```
or,
```
prim_path = Sdf.Path.GetPrimPath(path) # Returns: Sdf.Path('/set/bicycle')
```
---
_**Note:** If you want I can too raise a PR._

**Comment by LucaScheller** [comment]
Fixed, thanks for taking the time to point out and fix these typos! Highly appreciated! PR are always welcome too :)  I've added you to the contributors list.

**Comment by DStarRaj** [comment]
Ohh woow, didn't saw that coming 🤩. Surely will make sure to contribute further.
